/**
 * Pane Backup Engine v2 — Smart Export
 *
 * Creates a lean backup by stripping noise from SQLite databases
 * before uploading. Instead of brute-force .backup() (which copies
 * everything including 1 GB of embeddings + version noise), we
 * create optimized export copies.
 *
 * Optimization results (verified on a real 80-day dataset):
 *   brain.db:  1,141 MB → 367 MB (DROP node_versions, symbols, file_relationships
 *               and NULL embeddings; these are all recreatable at restoral)
 *   pane.db:     231 MB → 107 MB (DROP token_usage, quality_metrics, messages_fts
 *               — analytics noise and recreatable search index)
 *   Combined: 1,372 MB → 474 MB raw → ~30 MB gzipped (97.5% reduction over wire)
 *
 * What gets backed up:
 *   brain-opt.db   — knowledge graph w/o embeddings or code caches
 *   pane-opt.db    — conversations, edits, corrections w/o analytics noise
 *   routing-store.db — as-is (1.4 MB)
 *   profile/       — identity, rules, philosophy
 *   session/       — handoff state per project
 *   memory/        — event logs per project
 *   plans/         — plan history
 *   state/         — MCP / project state
 *   checkpoint/    — file snapshots
 *
 * What gets skipped (recreatable):
 *   node_versions    — confidence bump noise (141 MB, 88% "re-encountered")
 *   symbols          — codebase index (34 MB, rebuilt on project open)
 *   file_relationships — import graph (6 MB, rebuilt on project open)
 *   embeddings       — must be (354 MB, auto-regenerated by brain-engine)
 *   token_usage      — analytics (28 MB, NOT restored)
 *   quality_metrics  — analytics (6 MB, NOT restored)
 *   messages_fts     — search index (33 MB, rebuilt from messages table)
 *   brain/context/   — JSON exports (recreated from brain.db)
 *   brain/exports/   — JSON exports (recreated from brain.db)
 *   brain/symbols/   — JSON exports (recreated from brain.db)
 *   change-history/  — JSON session records (superseded by pane.db change_history)
 *
 * Post-restore regeneration (automatic on next startup):
 *   1. fillNullEmbeddings() — brain-engine embeds all nodes with NULL embeddings
 *   2. indexProjectSymbols() — triggered on project open when symbols table is empty
 *   3. rebuildFtsIndex() — called by restore handler, populates messages_fts from messages
 */

import fs from "node:fs/promises";
import { existsSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import os from "node:os";
import { ipcMain, BrowserWindow } from "electron";
import { isLoggedIn } from "./cloud-auth.mjs";
import { uploadBackup } from "./cloud-sync.mjs";

const require2 = createRequire(import.meta.url);

const PANE_DIR  = path.join(os.homedir(), ".pane");
const BACKUP_ROOT = path.join(PANE_DIR, "backups");
const KEEP_DAYS = 7;

// Directories copied recursively (relative to PANE_DIR) — small, critical state.
// These are JSON files, not the heavy SQLite databases.
const COPY_DIRS = [
  "session",
  "memory",
  "profile",
  "plans",
  "state",
  "checkpoint",
];

// SQLite databases that get the optimized-export treatment
// relPath: relative path within backup dir — uses original paths so
// restore "just works" by copying files back to ~/.pane/ locations.
const EXPORT_DBS = [
  {
    label: "brain",
    src: path.join(PANE_DIR, "brain", "brain.db"),
    relPath: "brain/brain.db",
    noiseTables: ["node_versions", "symbols", "file_relationships"],
    noiseUpdate: "UPDATE nodes SET embedding = NULL",
  },
  {
    label: "pane",
    src: path.join(PANE_DIR, "pane.db"),
    relPath: "pane.db",
    noiseTables: ["token_usage", "quality_metrics"],
    noiseFtsDrop: true,
    noiseUpdate: null,
  },
];

// Single-file databases copied as-is (too small to bother optimizing)
const COPY_DBS = [
  { src: path.join(PANE_DIR, "routing-store.db"), destName: "routing-store.db" },
];

// Flat files copied directly (relative to PANE_DIR)
const COPY_FILES = [
  "benchmark-scout.json",
];

// Temporary directory for optimized exports (cleaned up after each backup)
const TMP_DIR = path.join(PANE_DIR, "tmp", "backup-export");

// ---------------------------------------------------------------------------
// Optimized SQLite export — creates a lean DB without noise tables/columns
// ---------------------------------------------------------------------------

/**
 * Create an optimized copy of a SQLite database by removing noise tables
 * and heavy but recreatable columns.
 *
 * Uses .backup() first (handles WAL + active writers correctly), then
 * opens the copy and removes noise.
 *
 * @param {string} srcPath  — path to the live database
 * @param {string} destPath — path for the optimized export
 * @param {object} opts
 * @param {string[]} opts.noiseTables — table names to DROP entirely
 * @param {boolean} [opts.noiseFtsDrop] — if true, drop all messages_fts* tables
 * @param {string|null} [opts.noiseUpdate] — SQL to null-out heavy columns
 * @returns {Promise<number>} final file size in bytes
 */
async function createOptimizedDbExport(srcPath, destPath, opts) {
  if (!existsSync(srcPath)) return 0;

  mkdirSync(path.dirname(destPath), { recursive: true });

  // Step 1: Live backup (handles WAL correctly)
  let srcDb = null;
  try {
    const Database = require2("better-sqlite3");
    srcDb = new Database(srcPath, { readonly: true });
    await srcDb.backup(destPath);
  } finally {
    if (srcDb) {
      try { srcDb.close(); } catch {
        // Non-critical: backup already completed, process will reclaim FDs on exit
      }
    }
  }

  // Step 2: Open the copy and remove noise
  const db = new require2("better-sqlite3")(destPath);
  try {
    db.pragma("journal_mode = DELETE"); // VACUUM requires non-WAL
    db.pragma("synchronous = OFF");     // Faster VACUUM — we don't need crash safety for temp exports

    // Drop noise tables
    for (const table of opts.noiseTables) {
      try {
        db.exec(`DROP TABLE IF EXISTS [${table}]`);
      } catch (err) {
        console.warn(`[backup] ${path.basename(destPath)}: failed to drop ${table}: ${err.message}`);
      }
    }

    // Drop FTS tables if requested (messages_fts + shadow tables)
    if (opts.noiseFtsDrop) {
      const ftsTables = [
        "messages_fts",
        "messages_fts_data",
        "messages_fts_idx",
        "messages_fts_content",
        "messages_fts_docsize",
        "messages_fts_config",
      ];
      for (const table of ftsTables) {
        try {
          db.exec(`DROP TABLE IF EXISTS [${table}]`);
        } catch (err) {
          console.warn(`[backup] ${path.basename(destPath)}: failed to drop ${table}: ${err.message}`);
        }
      }
      // Drop the trigger that references FTS (would fail on INSERT otherwise)
      try {
        db.exec("DROP TRIGGER IF EXISTS messages_fts_delete");
      } catch {
        // Non-critical: trigger may not exist if already dropped or DB doesn't have one
      }
    }

    // Null out heavy columns
    if (opts.noiseUpdate) {
      db.exec(opts.noiseUpdate);
    }

    // VACUUM to reclaim space
    db.exec("VACUUM");

    const stat = await fs.stat(destPath);
    return stat.size;
  } finally {
    db.close();
  }
}

// ---------------------------------------------------------------------------
// Directory / file copy helpers (unchanged from v1)
// ---------------------------------------------------------------------------

async function copyDir(src, dest) {
  if (!existsSync(src)) return;
  mkdirSync(dest, { recursive: true });
  await fs.cp(src, dest, { recursive: true, errorOnExist: false, force: true });
}

async function copyFile(src, dest) {
  if (!existsSync(src)) return;
  mkdirSync(path.dirname(dest), { recursive: true });
  await fs.copyFile(src, dest);
}

// ---------------------------------------------------------------------------
// Rotation — keep only the most recent KEEP_DAYS backups
// ---------------------------------------------------------------------------

async function rotate() {
  let entries;
  try {
    entries = await fs.readdir(BACKUP_ROOT);
  } catch {
    return;
  }

  const dated = entries
    .filter(e => /^\d{4}-\d{2}-\d{2}$/.test(e))
    .sort();

  const toDelete = dated.slice(0, Math.max(0, dated.length - KEEP_DAYS));
  for (const name of toDelete) {
    try {
      await fs.rm(path.join(BACKUP_ROOT, name), { recursive: true, force: true });
      console.log("[backup] rotated out:", name);
    } catch (err) {
      console.warn("[backup] rotation failed for", name, err.message);
    }
  }
}

// ---------------------------------------------------------------------------
// Core backup run — creates optimized exports in a temp dir, then moves them
// ---------------------------------------------------------------------------

async function runBackup() {
  const tag = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const dest = path.join(BACKUP_ROOT, tag);
  const exportDir = path.join(TMP_DIR, tag);

  // Clean up any stale temp from a previous crash
  await fs.rm(exportDir, { recursive: true, force: true }).catch(() => {});
  mkdirSync(exportDir, { recursive: true });
  mkdirSync(dest, { recursive: true });

  console.log(`[backup] starting daily backup → ${dest}`);
  const t0 = Date.now();

  const tasks = [];

  // ── Optimized SQLite exports ────────────────────────────────────────
  for (const dbOpts of EXPORT_DBS) {
    const exportPath = path.join(exportDir, dbOpts.relPath.replace("/", "-"));
    tasks.push(
      createOptimizedDbExport(dbOpts.src, exportPath, dbOpts)
        .then(size => {
          if (size > 0) {
            console.log(`[backup] ${dbOpts.label}: ${(size / 1024 / 1024).toFixed(1)} MB`);
          }
          // Move to destination — uses relPath so restore maps to original paths
          if (existsSync(exportPath)) {
            const destPath = path.join(dest, dbOpts.relPath);
            mkdirSync(path.dirname(destPath), { recursive: true });
            return fs.cp(exportPath, destPath);
          }
        })
    );
  }

  // ── Direct database copies (small) ──────────────────────────────────
  for (const { src, destName } of COPY_DBS) {
    tasks.push(copyFile(src, path.join(dest, destName)));
  }

  // ── JSON state directories ──────────────────────────────────────────
  for (const dir of COPY_DIRS) {
    tasks.push(copyDir(path.join(PANE_DIR, dir), path.join(dest, dir)));
  }

  // ── Flat config files ───────────────────────────────────────────────
  for (const file of COPY_FILES) {
    tasks.push(copyFile(path.join(PANE_DIR, file), path.join(dest, file)));
  }

  const results = await Promise.allSettled(tasks);
  const failed  = results.filter(r => r.status === "rejected");
  if (failed.length > 0) {
    for (const f of failed) {
      console.warn("[backup] partial failure:", f.reason?.message ?? f.reason);
    }
  }

  // Clean up temp export directory
  await fs.rm(exportDir, { recursive: true, force: true }).catch(() => {});

  const elapsed = Date.now() - t0;
  console.log(`[backup] done in ${elapsed}ms (${failed.length} failures)`);

  // Rotate after successful backup
  await rotate();

  // Push to Pane Cloud if logged in
  try {
    if (isLoggedIn()) {
      await uploadBackup(dest);
    }
  } catch (err) {
    console.warn("[backup] cloud upload failed (non-fatal):", err.message);
    emitBackupProgress("error", { message: err.message });
  }

  return {
    tag,
    path: dest,
    failed_count: failed.length,
  };
}

// ---------------------------------------------------------------------------
// Schedule — fire at the next midnight, then every 24h
// ---------------------------------------------------------------------------

function msUntilMidnight() {
  const now  = new Date();
  const next = new Date(now);
  next.setHours(24, 0, 0, 0);
  return next - now;
}

export function startBackupSchedule() {
  const delay = msUntilMidnight();
  const hh = Math.floor(delay / 3_600_000);
  const mm = Math.floor((delay % 3_600_000) / 60_000);
  console.log(`[backup] next run in ${hh}h ${mm}m`);

  setTimeout(() => {
    runBackup().catch(err => console.error("[backup] run failed:", err.message));
    setInterval(() => {
      runBackup().catch(err => console.error("[backup] run failed:", err.message));
    }, 24 * 60 * 60 * 1000);
  }, delay);
}

// ---------------------------------------------------------------------------
// IPC handlers — "Back up now" button
// ---------------------------------------------------------------------------

export function registerBackupHandlers() {
  ipcMain.handle("cloud_trigger_backup", async () => {
    emitBackupProgress("compressing");
    try {
      const result = await Promise.race([
        runBackup(),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error("Backup timed out after 10 minutes")), 600_000)
        ),
      ]);
      if (!result) throw new Error("Backup failed");
      return { tag: result.tag, path: result.path };
    } catch (err) {
      const message = err instanceof Error ? err.message : "Backup failed";
      console.error("[backup] IPC handler error:", message);
      emitBackupProgress("error", { message });
      throw err;
    }
  });
}

// ---------------------------------------------------------------------------
// Progress events
// ---------------------------------------------------------------------------

function emitBackupProgress(phase, data = {}) {
  const win = BrowserWindow.getAllWindows()[0];
  if (win && !win.isDestroyed()) {
    win.webContents.send("cloud-sync-progress", { phase, ...data });
  }
}
